export type VenueCategory =
  | 'Bakery'
  | 'Cafe'
  | 'Restaurant'
  | 'Dessert'
  | 'Late night'
  | 'Counter'

export type Venue = {
  id: string
  name: string
  category: VenueCategory
  neighborhood: string
  address: string
  lat: number
  lng: number
  signature: string[]
  imageEvidenceHints: string[]
  visualClues?: string[]
  menuClues?: string[]
  doNotInferFrom?: string[]
  multiLocation?: boolean
  sourceConfidence?: 'source-backed' | 'needs-review'
  sourceUrl: string
  mapsUrl: string
  note: string
}

export const venues: Venue[] = [
  {
    id: 'san-ho-won',
    name: 'San Ho Won',
    category: 'Restaurant',
    neighborhood: 'Mission',
    address: '2170 Bryant St',
    lat: 37.76044,
    lng: -122.41033,
    signature: ['Korean barbecue', 'charcoal grill', 'banchan', 'double-cut galbi'],
    imageEvidenceHints: ['korean', 'bbq', 'galbi', 'charcoal', 'mission', 'michelin', 'banchan', 'warehouse', 'bryant'],
    sourceUrl: 'https://www.sanhowon.com/',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=San+Ho+Won+2170+Bryant+St+San+Francisco',
    note: 'Modern Korean spot in the Mission with a charcoal-grill identity.',
  },
  {
    id: 'yamo',
    name: 'Yamo',
    category: 'Counter',
    neighborhood: 'Mission',
    address: '3406 18th St',
    lat: 37.76176,
    lng: -122.41986,
    signature: ['Burmese noodles', 'tiny counter', 'tea leaf salad'],
    imageEvidenceHints: ['burmese', 'noodles', 'counter', 'tiny', 'cash', 'mission', '18th', 'wok', 'tea leaf'],
    sourceUrl: 'https://www.yelp.com/biz/yamo-san-francisco',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Yamo+3406+18th+St+San+Francisco',
    note: 'Small Mission counter known for Burmese dishes and a narrow room.',
  },
  {
    id: 'rintaro',
    name: 'Rintaro',
    category: 'Restaurant',
    neighborhood: 'Mission',
    address: '82 14th St',
    lat: 37.76844,
    lng: -122.41563,
    signature: ['Izakaya', 'yakitori', 'handmade udon'],
    imageEvidenceHints: ['izakaya', 'yakitori', 'udon', 'japanese', 'mission', 'wood', 'courtyard', '14th'],
    sourceUrl: 'https://www.izakayarintaro.com/',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Rintaro+82+14th+St+San+Francisco',
    note: 'Mission izakaya with yakitori, handmade noodles, and a wood-heavy room.',
  },
  {
    id: 'la-taqueria',
    name: 'La Taqueria',
    category: 'Counter',
    neighborhood: 'Mission',
    address: '2889 Mission St',
    lat: 37.75101,
    lng: -122.41844,
    signature: ['Mission burrito', 'crispy tacos', 'carnitas'],
    imageEvidenceHints: ['burrito', 'mission', 'taco', 'carnitas', 'no rice', 'green awning', '24th'],
    sourceUrl: 'https://www.lataqueriasf.com/',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=La+Taqueria+2889+Mission+St+San+Francisco',
    note: 'Mission taqueria famous enough to be easy to confuse with several nearby spots.',
  },
  {
    id: 'el-farolito',
    name: 'El Farolito',
    category: 'Late night',
    neighborhood: 'Mission',
    address: '2779 Mission St',
    lat: 37.75266,
    lng: -122.41836,
    signature: ['Super burrito', 'late-night taqueria', 'al pastor'],
    imageEvidenceHints: ['burrito', 'late night', 'mission', 'super', 'al pastor', '24th', 'yellow sign', 'taqueria'],
    sourceUrl: 'https://elfarolitosf.com/',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=El+Farolito+2779+Mission+St+San+Francisco',
    note: 'Mission taqueria with a strong late-night evidence around 24th Street.',
  },
  {
    id: 'tartine-manufactory',
    name: 'Tartine Manufactory',
    category: 'Bakery',
    neighborhood: 'Mission',
    address: '595 Alabama St',
    lat: 37.76142,
    lng: -122.41161,
    signature: ['Morning bun', 'country bread', 'industrial bakery cafe'],
    imageEvidenceHints: ['morning bun', 'bread', 'bakery', 'mission', 'alabama', 'pastry', 'warehouse', 'tartine'],
    sourceUrl: 'https://tartinebakery.com/sanfrancisco/manufactory',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Tartine+Manufactory+595+Alabama+St+San+Francisco',
    note: 'Large Mission bakery-cafe tied to Tartine bread and pastries.',
  },
  {
    id: 'dandelion-chocolate',
    name: 'Dandelion Chocolate',
    category: 'Dessert',
    neighborhood: 'Mission',
    address: '740 Valencia St',
    lat: 37.76198,
    lng: -122.42162,
    signature: ['Bean-to-bar chocolate', 'hot chocolate', 'brownie flight'],
    imageEvidenceHints: ['chocolate', 'hot chocolate', 'valencia', 'mission', 'factory', 'brownie', 'bean to bar'],
    sourceUrl: 'https://www.dandelionchocolate.com/pages/visit-us',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Dandelion+Chocolate+740+Valencia+St+San+Francisco',
    note: 'Mission chocolate cafe and factory experience on Valencia.',
  },
  {
    id: 'breadbelly',
    name: 'Breadbelly',
    category: 'Bakery',
    neighborhood: 'Inner Richmond',
    address: '1408 Clement St',
    lat: 37.78232,
    lng: -122.47307,
    signature: ['Asian American pastries', 'kaya toast', 'milk bread'],
    imageEvidenceHints: ['kaya', 'toast', 'milk bread', 'clement', 'richmond', 'asian pastry', 'black sesame', 'bakery'],
    sourceUrl: 'https://www.breadbellysf.com/',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Breadbelly+1408+Clement+St+San+Francisco',
    note: 'Clement Street bakery with Asian American pastry cues.',
  },
  {
    id: 'cinderella-bakery',
    name: 'Cinderella Bakery',
    category: 'Bakery',
    neighborhood: 'Inner Richmond',
    address: '436 Balboa St',
    lat: 37.77764,
    lng: -122.46411,
    signature: ['Russian bakery', 'piroshki', 'borscht'],
    imageEvidenceHints: ['russian', 'piroshki', 'borscht', 'balboa', 'richmond', 'bakery', 'pelmeni', 'blini'],
    sourceUrl: 'https://www.cinderellabakery.com/',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Cinderella+Bakery+436+Balboa+St+San+Francisco',
    note: 'Inner Richmond Russian bakery and cafe with savory pastry image evidence.',
  },
  {
    id: 'arsicault',
    name: 'Arsicault Bakery',
    category: 'Bakery',
    neighborhood: 'Inner Richmond',
    address: '397 Arguello Blvd',
    lat: 37.78317,
    lng: -122.45912,
    signature: ['Croissants', 'kouign-amann', 'morning pastry line'],
    imageEvidenceHints: ['croissant', 'kouign amann', 'arguello', 'richmond', 'bakery', 'line', 'french pastry'],
    sourceUrl: 'https://www.arsicault-bakery.com/',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Arsicault+Bakery+397+Arguello+Blvd+San+Francisco',
    note: 'Richmond bakery where pastry-line image evidence usually matter.',
  },
  {
    id: 'kissaten-hifi',
    name: 'Kissaten HiFi',
    category: 'Cafe',
    neighborhood: 'Inner Richmond',
    address: '189 6th Ave',
    lat: 37.78526,
    lng: -122.4647,
    signature: ['Iced matcha', 'cream-top drinks', 'Filipino-Japanese cafe', 'vinyl records'],
    imageEvidenceHints: [
      'kissaten',
      'hifi',
      'hi-fi',
      'matcha',
      'cream top',
      'vinyl',
      'records',
      'brown coffee bags',
      'tan aprons',
      'inner richmond',
      '6th ave',
      'mango lassi matcha',
      'sightglass',
    ],
    visualClues: ['brown coffee bags on shelves', 'tan aprons', 'vinyl/listening-cafe cues', 'compact prep area'],
    menuClues: ['iced matcha', 'cream-top drinks', 'mango lassi matcha', 'coffee'],
    doNotInferFrom: ['generic matcha alone', 'brown bags alone', 'small animal/wall mark alone'],
    multiLocation: false,
    sourceConfidence: 'source-backed',
    sourceUrl: 'https://www.theinfatuation.com/san-francisco/reviews/kissaten-hifi',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Kissaten+HiFi+189+6th+Ave+San+Francisco',
    note: 'Recently opened Richmond coffee and matcha cafe with vinyl-listening cues and layered matcha drinks.',
  },
  {
    id: 'b-patisserie',
    name: 'B. Patisserie',
    category: 'Bakery',
    neighborhood: 'Lower Pacific Heights',
    address: '2821 California St',
    lat: 37.78776,
    lng: -122.44066,
    signature: ['Kouign-amann', 'French pastries', 'California Street cafe'],
    imageEvidenceHints: ['kouign amann', 'pastry', 'california street', 'pac heights', 'french', 'bakery', 'line'],
    sourceUrl: 'https://bpatisserie.com/',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=B.+Patisserie+2821+California+St+San+Francisco',
    note: 'Lower Pac Heights pastry shop with strong kouign-amann evidence.',
  },
  {
    id: 'good-luck-dim-sum',
    name: 'Good Luck Dim Sum',
    category: 'Counter',
    neighborhood: 'Inner Richmond',
    address: '736 Clement St',
    lat: 37.78259,
    lng: -122.46642,
    signature: ['Takeout dim sum', 'har gow', 'siu mai'],
    imageEvidenceHints: ['dim sum', 'har gow', 'siu mai', 'clement', 'richmond', 'takeout', 'cash', 'dumpling'],
    sourceUrl: 'https://www.yelp.com/biz/good-luck-dim-sum-san-francisco',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Good+Luck+Dim+Sum+736+Clement+St+San+Francisco',
    note: 'Clement Street takeout dim sum counter.',
  },
  {
    id: 'sam-wo',
    name: 'Sam Wo',
    category: 'Restaurant',
    neighborhood: 'Chinatown',
    address: '713 Clay St',
    lat: 37.79408,
    lng: -122.40643,
    signature: ['Chinatown classic', 'rice noodle rolls', 'BBQ pork'],
    imageEvidenceHints: ['chinatown', 'clay', 'noodle roll', 'jook', 'bbq pork', 'old school', 'sam wo'],
    sourceUrl: 'https://www.samworestaurant.com/',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Sam+Wo+713+Clay+St+San+Francisco',
    note: 'Chinatown classic with old-school visual and menu cues.',
  },
  {
    id: 'mister-jius',
    name: "Mister Jiu's",
    category: 'Restaurant',
    neighborhood: 'Chinatown',
    address: '28 Waverly Pl',
    lat: 37.79341,
    lng: -122.40637,
    signature: ['Modern Chinese', 'Waverly Place', 'banquet room'],
    imageEvidenceHints: ['chinatown', 'waverly', 'modern chinese', 'duck', 'mister jiu', 'michelin', 'lanterns'],
    sourceUrl: 'https://www.misterjius.com/',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Mister+Jiu%27s+28+Waverly+Pl+San+Francisco',
    note: 'Modern Chinese restaurant tucked on Waverly Place.',
  },
  {
    id: 'z-and-y',
    name: 'Z & Y Restaurant',
    category: 'Restaurant',
    neighborhood: 'Chinatown',
    address: '655 Jackson St',
    lat: 37.7961,
    lng: -122.40703,
    signature: ['Sichuan', 'Chinatown', 'spicy chicken'],
    imageEvidenceHints: ['sichuan', 'szechuan', 'spicy', 'chinatown', 'jackson', 'chili', 'dan dan'],
    sourceUrl: 'https://www.zandyrestaurant.com/',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Z+and+Y+Restaurant+655+Jackson+St+San+Francisco',
    note: 'Chinatown Sichuan restaurant with high chili and spice image evidence.',
  },
  {
    id: 'golden-boy',
    name: 'Golden Boy Pizza',
    category: 'Counter',
    neighborhood: 'North Beach',
    address: '542 Green St',
    lat: 37.79971,
    lng: -122.40808,
    signature: ['Focaccia pizza', 'clam garlic slice', 'cash line'],
    imageEvidenceHints: ['pizza', 'focaccia', 'clam', 'north beach', 'green street', 'slice', 'square', 'neon'],
    sourceUrl: 'https://www.goldenboypizza.com/',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Golden+Boy+Pizza+542+Green+St+San+Francisco',
    note: 'North Beach slice counter known for focaccia-style squares.',
  },
  {
    id: 'liguria-bakery',
    name: 'Liguria Bakery',
    category: 'Bakery',
    neighborhood: 'North Beach',
    address: '1700 Stockton St',
    lat: 37.80063,
    lng: -122.40958,
    signature: ['Focaccia', 'early sellout', 'Washington Square'],
    imageEvidenceHints: ['focaccia', 'north beach', 'stockton', 'washington square', 'bakery', 'early', 'cash'],
    sourceUrl: 'https://www.yelp.com/biz/liguria-bakery-san-francisco',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Liguria+Bakery+1700+Stockton+St+San+Francisco',
    note: 'Old North Beach focaccia bakery by Washington Square.',
  },
  {
    id: 'sotto-mare',
    name: 'Sotto Mare',
    category: 'Restaurant',
    neighborhood: 'North Beach',
    address: '552 Green St',
    lat: 37.79974,
    lng: -122.40825,
    signature: ['Cioppino', 'seafood counter', 'North Beach'],
    imageEvidenceHints: ['cioppino', 'seafood', 'north beach', 'green street', 'crab', 'fish', 'white awning'],
    sourceUrl: 'https://www.sottomaresf.com/',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Sotto+Mare+552+Green+St+San+Francisco',
    note: 'Seafood-heavy North Beach restaurant next to other Green Street classics.',
  },
  {
    id: 'cafe-jacqueline',
    name: 'Cafe Jacqueline',
    category: 'Restaurant',
    neighborhood: 'North Beach',
    address: '1454 Grant Ave',
    lat: 37.79909,
    lng: -122.40764,
    signature: ['Souffles', 'French bistro', 'tiny dining room'],
    imageEvidenceHints: ['souffle', 'souffles', 'french', 'north beach', 'grant', 'tiny', 'date night'],
    sourceUrl: 'https://www.cafejacqueline.com/',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Cafe+Jacqueline+1454+Grant+Ave+San+Francisco',
    note: 'Tiny North Beach restaurant strongly associated with souffles.',
  },
  {
    id: 'outerlands',
    name: 'Outerlands',
    category: 'Restaurant',
    neighborhood: 'Outer Sunset',
    address: '4001 Judah St',
    lat: 37.76079,
    lng: -122.50469,
    signature: ['Brunch', 'Dutch pancake', 'coastal wood interior'],
    imageEvidenceHints: ['outer sunset', 'judah', 'brunch', 'toast', 'dutch pancake', 'wood', 'beach', 'surf'],
    sourceUrl: 'https://outerlandssf.com/',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Outerlands+4001+Judah+St+San+Francisco',
    note: 'Outer Sunset brunch and dinner spot with coastal, wood-lined cues.',
  },
  {
    id: 'trouble-coffee',
    name: 'Trouble Coffee',
    category: 'Cafe',
    neighborhood: 'Outer Sunset',
    address: '4033 Judah St',
    lat: 37.76073,
    lng: -122.50583,
    signature: ['Coffee', 'cinnamon toast', 'coconuts'],
    imageEvidenceHints: ['coffee', 'cinnamon toast', 'coconut', 'outer sunset', 'judah', 'surf', 'tiny cafe'],
    sourceUrl: 'https://www.trouble.coffee/',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Trouble+Coffee+4033+Judah+St+San+Francisco',
    note: 'Outer Sunset cafe with cinnamon toast and beach-neighborhood cues.',
  },
  {
    id: 'hook-fish',
    name: 'Hook Fish Co.',
    category: 'Restaurant',
    neighborhood: 'Outer Sunset',
    address: '4542 Irving St',
    lat: 37.76274,
    lng: -122.50699,
    signature: ['Fish tacos', 'poke', 'surf crowd'],
    imageEvidenceHints: ['fish taco', 'poke', 'outer sunset', 'irving', 'surf', 'seafood', 'patio', 'beach'],
    sourceUrl: 'https://www.hookfishco.com/',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Hook+Fish+Co+4542+Irving+St+San+Francisco',
    note: 'Outer Sunset seafood spot close to Ocean Beach.',
  },
  {
    id: 'devils-teeth',
    name: "Devil's Teeth Baking Company",
    category: 'Bakery',
    neighborhood: 'Outer Sunset',
    address: '3876 Noriega St',
    lat: 37.75388,
    lng: -122.50415,
    signature: ['Breakfast sandwich', 'beignets', 'Noriega bakery'],
    imageEvidenceHints: ['breakfast sandwich', 'beignets', 'noriega', 'outer sunset', 'bakery', 'special breakfast sandwich'],
    sourceUrl: 'https://www.devilsteethbakingcompany.com/',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Devil%27s+Teeth+Baking+Company+3876+Noriega+St+San+Francisco',
    note: 'Outer Sunset bakery best guessed from breakfast sandwich image evidence.',
  },
  {
    id: 'toyose',
    name: 'Toyose',
    category: 'Late night',
    neighborhood: 'Outer Sunset',
    address: '3814 Noriega St',
    lat: 37.75385,
    lng: -122.50326,
    signature: ['Korean late night', 'garage restaurant', 'soju'],
    imageEvidenceHints: ['korean', 'late night', 'garage', 'soju', 'noriega', 'outer sunset', 'wings', 'army stew'],
    sourceUrl: 'https://sf.eater.com/venue/55498/toyose',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Toyose+3814+Noriega+St+San+Francisco',
    note: 'Outer Sunset Korean spot often identified by the garage-room evidence.',
  },
  {
    id: 'san-tung',
    name: 'San Tung',
    category: 'Restaurant',
    neighborhood: 'Inner Sunset',
    address: '1031 Irving St',
    lat: 37.76377,
    lng: -122.46888,
    signature: ['Dry fried chicken wings', 'Chinese-Korean dishes'],
    imageEvidenceHints: ['wings', 'dry fried', 'chicken', 'irving', 'inner sunset', 'line', 'chinese korean'],
    sourceUrl: 'https://www.santungsf.com/',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=San+Tung+1031+Irving+St+San+Francisco',
    note: 'Inner Sunset restaurant with a very specific dry-fried wing evidence.',
  },
  {
    id: 'arizmendi',
    name: 'Arizmendi Bakery',
    category: 'Bakery',
    neighborhood: 'Inner Sunset',
    address: '1331 9th Ave',
    lat: 37.76338,
    lng: -122.46621,
    signature: ['Co-op bakery', 'daily pizza slice', 'scones'],
    imageEvidenceHints: ['pizza slice', 'co-op', 'inner sunset', '9th ave', 'bakery', 'scone', 'cheese roll'],
    sourceUrl: 'https://www.arizmendibakery.com/',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Arizmendi+Bakery+1331+9th+Ave+San+Francisco',
    note: 'Inner Sunset co-op bakery with rotating pizza-slice image evidence.',
  },
  {
    id: 'pineapple-king',
    name: 'Pineapple King Bakery',
    category: 'Bakery',
    neighborhood: 'Inner Sunset',
    address: '1915 Irving St',
    lat: 37.76356,
    lng: -122.4779,
    signature: ['Pineapple buns', 'bolo bao', 'Hong Kong bakery'],
    imageEvidenceHints: ['pineapple bun', 'bolo bao', 'hong kong', 'irving', 'inner sunset', 'bakery', 'custard'],
    sourceUrl: 'https://www.pineapplekingbakery.com/',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Pineapple+King+Bakery+1915+Irving+St+San+Francisco',
    note: 'Irving Street bakery with pineapple bun and Hong Kong pastry cues.',
  },
  {
    id: 'dumpling-specialist',
    name: 'Dumpling Specialist',
    category: 'Counter',
    neighborhood: 'Outer Sunset',
    address: '1123 Taraval St',
    lat: 37.74266,
    lng: -122.47844,
    signature: ['Sheng jian bao', 'dumplings', 'Taraval counter'],
    imageEvidenceHints: ['dumpling', 'sheng jian bao', 'taraval', 'outer sunset', 'potsticker', 'xiao long bao'],
    sourceUrl: 'https://www.yelp.com/biz/dumpling-specialist-san-francisco',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Dumpling+Specialist+1123+Taraval+St+San+Francisco',
    note: 'Taraval counter where dumpling-specific image evidence is useful.',
  },
  {
    id: 'thanh-long',
    name: 'Thanh Long',
    category: 'Restaurant',
    neighborhood: 'Outer Sunset',
    address: '4101 Judah St',
    lat: 37.7605,
    lng: -122.50743,
    signature: ['Roast crab', 'garlic noodles', 'Vietnamese seafood'],
    imageEvidenceHints: ['garlic noodles', 'roast crab', 'outer sunset', 'judah', 'vietnamese', 'seafood', 'crab'],
    sourceUrl: 'https://www.thanhlongsf.com/',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Thanh+Long+4101+Judah+St+San+Francisco',
    note: 'Outer Sunset seafood institution tied to roast crab and garlic noodles.',
  },
  {
    id: 'dumpling-home',
    name: 'Dumpling Home',
    category: 'Restaurant',
    neighborhood: 'Hayes Valley',
    address: '298 Gough St',
    lat: 37.77724,
    lng: -122.42268,
    signature: ['Xiao long bao', 'pan-fried dumplings', 'colorful dumplings'],
    imageEvidenceHints: ['dumpling', 'xiao long bao', 'xlb', 'hayes', 'gough', 'pan fried', 'colorful'],
    sourceUrl: 'https://www.dumplinghome.com/',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Dumpling+Home+298+Gough+St+San+Francisco',
    note: 'Hayes Valley dumpling spot with soup dumpling and colorful basket image evidence.',
  },
  {
    id: 'rt-bistro',
    name: 'RT Bistro',
    category: 'Restaurant',
    neighborhood: 'Hayes Valley',
    address: '205 Oak St',
    lat: 37.77485,
    lng: -122.42295,
    signature: ['Rich Table team', 'bistro burger', 'porcini doughnuts', 'caviar', 'single-layer lasagna'],
    imageEvidenceHints: [
      'rt bistro',
      'rich table',
      'hayes valley',
      'oak st',
      'burger',
      'caviar',
      'porcini',
      'doughnuts',
      'single-layer lasagna',
      'duck a l orange',
      'bistro',
    ],
    visualClues: ['bistro burger plating', 'caviar service when paired with RT Bistro context', 'Hayes Valley bistro setting'],
    menuClues: ['bistro burger', 'porcini doughnuts', 'caviar', 'single-layer lasagna'],
    doNotInferFrom: ['caviar word alone', 'generic burger alone', 'Rich Table mention without uploaded-photo support'],
    multiLocation: false,
    sourceConfidence: 'source-backed',
    sourceUrl: 'https://www.rt-bistro.com/menus/',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=RT+Bistro+205+Oak+St+San+Francisco',
    note: 'New Hayes Valley bistro from the Rich Table team; caviar or burger clues should not be mistaken for unrelated caviar cafes.',
  },
  {
    id: 'house-of-prime-rib',
    name: 'House of Prime Rib',
    category: 'Restaurant',
    neighborhood: 'Nob Hill',
    address: '1906 Van Ness Ave',
    lat: 37.79344,
    lng: -122.42244,
    signature: ['Prime rib cart', 'martinis', 'old-school dining room'],
    imageEvidenceHints: ['prime rib', 'cart', 'van ness', 'nob hill', 'martini', 'old school', 'spinning salad'],
    sourceUrl: 'https://www.houseofprimerib.net/',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=House+of+Prime+Rib+1906+Van+Ness+Ave+San+Francisco',
    note: 'Classic Van Ness steakhouse where cart and spinning-salad image evidence is decisive.',
  },
  {
    id: 'bobs-donuts',
    name: "Bob's Donuts",
    category: 'Late night',
    neighborhood: 'Polk Gulch',
    address: '1621 Polk St',
    lat: 37.79166,
    lng: -122.42101,
    signature: ['Giant donut', '24-hour donut shop', 'Polk Street'],
    imageEvidenceHints: ['donut', 'giant donut', '24 hour', 'polk', 'late night', 'nob hill', 'apple fritter'],
    sourceUrl: 'https://www.bobsdonutssf.com/',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Bob%27s+Donuts+1621+Polk+St+San+Francisco',
    note: 'Polk Street donut shop with a giant-donut evidence that is hard to miss.',
  },
  {
    id: 'beit-rima',
    name: 'Beit Rima',
    category: 'Restaurant',
    neighborhood: 'Duboce Triangle',
    address: '138 Church St',
    lat: 37.76833,
    lng: -122.42929,
    signature: ['Arabic comfort food', 'mezze', 'bright tiled room'],
    imageEvidenceHints: ['arabic', 'mezze', 'hummus', 'church', 'duboce', 'tile', 'shish', 'kafta'],
    sourceUrl: 'https://www.beitrimasf.com/',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Beit+Rima+138+Church+St+San+Francisco',
    note: 'Duboce Triangle Arabic comfort-food spot with colorful tile cues.',
  },
  {
    id: 'kokkari',
    name: 'Kokkari Estiatorio',
    category: 'Restaurant',
    neighborhood: 'FiDi',
    address: '200 Jackson St',
    lat: 37.79711,
    lng: -122.39943,
    signature: ['Greek fine dining', 'fireplace', 'lamb chops'],
    imageEvidenceHints: ['greek', 'lamb', 'fireplace', 'fidi', 'jackson', 'rotisserie', 'estiatorio'],
    sourceUrl: 'https://kokkari.com/',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Kokkari+Estiatorio+200+Jackson+St+San+Francisco',
    note: 'FiDi Greek restaurant usually revealed by lamb, fireplace, or rotisserie cues.',
  },
  {
    id: 'souvla',
    name: 'Souvla',
    category: 'Restaurant',
    neighborhood: 'Multiple SF neighborhoods',
    address: 'Multiple San Francisco locations',
    lat: 37.77642,
    lng: -122.42484,
    signature: ['Greek salads', 'souvlaki', 'fries', 'frozen Greek yogurt'],
    imageEvidenceHints: [
      'souvla',
      'greek',
      'blue rim',
      'greek key',
      'fries',
      'frozen greek yogurt',
      'souvlaki',
      'salad',
      'pita',
      'rotisserie',
      'hayes',
      'divisadero',
      'valencia',
      'chestnut',
      'dogpatch',
    ],
    visualClues: ['readable Souvla text', 'Greek key tray liner', 'blue-rim enamel-style plates', 'rotisserie counter context'],
    menuClues: ['souvlaki', 'Greek salads', 'fries', 'frozen Greek yogurt'],
    doNotInferFrom: ['generic Greek food alone', 'blue-rim plates without visible Souvla text', 'one SF branch without GPS or neighborhood clues'],
    multiLocation: true,
    sourceConfidence: 'source-backed',
    sourceUrl: 'https://www.souvla.com/locations/',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Souvla+San+Francisco',
    note: 'San Francisco-born Greek restaurant group; exact branch should be confirmed from GPS, storefront, or neighborhood clues.',
  },
  {
    id: 'bodega-sf',
    name: 'Bodega SF',
    category: 'Restaurant',
    neighborhood: 'Tenderloin',
    address: '138 Mason St',
    lat: 37.78431,
    lng: -122.40959,
    signature: ['Modern Vietnamese', 'garlic noodles', 'shaking beef'],
    imageEvidenceHints: ['vietnamese', 'bodega', 'tenderloin', 'mason', 'garlic noodles', 'shaking beef', 'pho'],
    visualClues: ['readable Bodega SF venue text', 'Tenderloin/Mason Street context'],
    menuClues: ['garlic noodles', 'shaking beef', 'pho'],
    doNotInferFrom: ['partial BODEGA text on third-party packaging', 'generic Vietnamese dishes without venue text'],
    multiLocation: false,
    sourceConfidence: 'source-backed',
    sourceUrl: 'https://www.bodegasf.com/',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Bodega+SF+138+Mason+St+San+Francisco',
    note: 'Tenderloin Vietnamese restaurant with modern dining-room cues.',
  },
]

export const categoryOptions: Array<'All' | VenueCategory> = [
  'All',
  'Restaurant',
  'Bakery',
  'Cafe',
  'Dessert',
  'Counter',
  'Late night',
]
